import LocalizedStrings from "react-localization";

const prestrings = {
  searchPlaceholder: {
    en: "Search Books, Audiobooks, Podcasts",
    kg: "Китептерди, аудиокитептерди, подкасттарды издөө",
    ru: "Искать Книги, Аудиокниги, Подкасты",
    tj: "Ҷустуҷӯйи китобҳо, Китобҳои аудиоӣ, Подкастҳо",
  },
  popularText: {
    en: "Popular",
    kg: "Популярдуу",
    ru: "Популярное",
    tj: "Машҳур",
  },
  bookBestSellers: {
    en: "Book Bestsellers",
    kg: "Китеп Бестселлерлери",
    ru: "Книжные Бестселлеры",
    tj: "Китобҳои бестселлер",
  },
  videoText: {
    en: "Video",
    kg: "Видео",
    ru: "Видео",
    tj: "Видео",
  },
  booksText: {
    en: "Books",
    kg: "Китептер",
    ru: "Книги",
    tj: "Китобҳо",
  },
  newsText: {
    en: "News",
    kg: "Жанылыктар",
    ru: "Новости",
    tj: "Хабарҳо",
  },
  nameText: {
    en: "Title",
    kg: "Аты-жөнү",
    ru: "Название",
    tj: "Номи китоб",
  },
  authorText: {
    en: "Author",
    kg: "Автор",
    ru: "Автор",
    tj: "Муаллиф",
  },
  sourceText: {
    en: "Source",
    kg: "Булак",
    ru: "Источник",
    tj: "Сарчашма",
  },
  publishYearText: {
    en: "Publish Year",
    kg: "Жарыялоо жылы",
    ru: "Год издания",
    tj: "Соли нашр",
  },
  descriptionText: {
    en: "Description",
    kg: "Сыпаттама",
    ru: "Описание",
    tj: "Тавсиф",
  },
  readText: {
    en: "Read",
    kg: "Оку",
    ru: "Читать",
    tj: "Хондан",
  },
  downloadText: {
    en: "Download",
    kg: "Көчүрү",
    ru: "Скачать",
    tj: "Сабт кардан",
  },
  saveText: {
    en: "Save",
    kg: "Сактоо",
    ru: "Сохранить",
    tj: "Нигоҳ доштан",
  },
  movePageText: {
    en: "Move",
    kg: "Жылдыруу",
    ru: "Перейти",
    tj: "Гузаштан",
  },
  viwsText: {
    en: "views",
    kg: "көрүүлөр",
    ru: "просмотров",
    tj: "назари",
  },
  uploadDateText: {
    en: "Date added",
    kg: "Датасы кошулган",
    ru: "Дата добовления",
    tj: "санаи иловашуда",
  },
  govResourcesText: {
    en: "State Sources of Information and News",
    kg: "Мамлекеттик маалымат жана кабар булактары",
    ru: "Государственные источники информации и Новости",
    tj: "Манбаъхои давлатии иттилоот ва ахбор",
  },
  Login_and_Registration: {
    en: "Login and Registration",
    kg: "Login and Registration kg",
    ru: "Login and Registration ru",
    tj: "",
  },
  email: {
    en: "Email",
    kg: "Email kg",
    ru: "Email ru",
    tj: "",
  },
  phone_number: {
    en: "phone number",
    kg: "phone number kg",
    ru: "phone number ru",
    tj: "",
  },
  continue: {
    en: "continue en",
    kg: "continue kg",
    ru: "continue ru",
    tj: "",
  },
  enter_email_address: {
    en: "Enter email address",
    kg: "Enter email address kg",
    ru: "Enter email address ru",
    tj: "",
  },
  enter_phone_number: {
    en: "Enter phone number",
    kg: "Enter phone number kg",
    ru: "Enter phone number ru",
    tj: "",
  },
  Book_Bestsellers: {
    en: "Book_Bestsellers",
    kg: "Китеп бестселлерлери",
    ru: "Книжные бестселлеры",
    tj: "Китобҳои бестселлер",
  },
  Audio_Books: {
    en: "Audio_Books",
    kg: "Audio_Books kg",
    ru: "Audio_Books ru",
    tj: "",
  },
  Videos: {
    en: "Videos",
    kg: "Видео",
    ru: "Видео",
    tj: "Видео",
  },
  Catalog: {
    en: "Catalog",
    ru: "Каталог",
    kg: "Каталог",
    tj: "Каталог",
  },
  Rating: {
    en: "Rating",
    ru: "Rating ru",
    kg: "Rating kg",
    tj: "",
  },
  Year: {
    en: "Year",
    ru: "Year ru",
    kg: "Year kg",
    tj: "",
  },
  Genre: {
    en: "Genre",
    ru: "Genre ru",
    kg: "Genre kg",
    tj: "",
  },
  translateDate: {
    en: "publish year",
    ru: "Год издания",
    kg: "Жарыялоо жылы",
    tj: "Соли нашр",
  },
  Listen: {
    en: "Listen",
    ru: "Listen ru",
    kg: "Listen kg",
    tj: "",
  },
};

const strings = new LocalizedStrings(
  Object.keys(prestrings).reduce(
    (dictionary, word) => ({
      ...Object.keys(prestrings[word]).reduce(
        (acc, lang) => ({
          ...acc,
          [lang]: { [word]: prestrings[word][lang], ...dictionary[lang] },
        }),
        {}
      ),
    }),
    {}
  )
);
// const strings = new LocalizedStrings({
//   ru: {
//     searchPlaceholder: "Искать Книги, Аудиокниги, Подкасты",
//     popularText: "Популярное",
//     bookBestSellers: "Книжные Бестселлеры",
//     videoText: "Видео",
//     booksText: "Книги",
//     newsText: "Новости",
//     nameText: "Название",
//     authorText: "Автор",
//     sourceText: "Источник",
//     publishYearText: "Год издания",
//     descriptionText: "Описание",
//     readText: "Читать",
//     downloadText: "Скачать",
//     saveText: "Сохранить",
//     movePageText: "Перейти",
//     viwsText: "просмотров",
//     uploadDateText: "Дата добовления",
//     govResourcesText: "Государственные источники информации и Новости",
//   },
//   kg: {
//     searchPlaceholder: "Китептерди, аудиокитептерди, подкасттарды издөө",
//     popularText: "Популярдуу",
//     bookBestSellers: "Китеп Бестселлерлери",
//     videoText: "Видео",
//     booksText: "Китептер",
//     newsText: "Жанылыктар",
//     nameText: "Аты-жөнү",
//     authorText: "Автор",
//     sourceText: "Булак",
//     publishYearText: "Жарыялоо жылы",
//     descriptionText: "Сыпаттама",
//     readText: "Оку",
//     downloadText: "Көчүрү",
//     saveText: "Сактоо",
//     movePageText: "Жылдыруу",
//     viwsText: "көрүүлөр",
//     uploadDateText: "Датасы кошулган",
//  govResourcesText: "Мамлекеттик маалымат жана кабар булактары",
//   },
//   en: {
//     searchPlaceholder: "Search Books, Audiobooks, Podcasts",
//     popularText: "Popular",
//     bookBestSellers: "Book Bestsellers",
//     videoText: "Video",
//     booksText: "Books",
//     newsText: "News",
//     nameText: "Title",
//     authorText: "Author",
//     sourceText: "Source",
//     publishYearText: "Publish Year",
//     descriptionText: "Description",
//     readText: "Read",
//     downloadText: "Download",
//     saveText: "Save",
//     movePageText: "Move",
//     viwsText: "views",
//     uploadDateText: "Date added",
//     govResourcesText: "State Sources of Information and News",
//   },
// });
export { strings };
